all:
  vars:
    env: "YOUR Environment"
    subnet: "YOUR Subnet"

    switches:
      hosts:
        SW01:
         ansible_host: "{{ subnet }}.YOUR.IP"
        SW02:
         ansible_host: "{{ subnet }}.YOUR.IP"
